NETWORK_ENDIAN = '!'
BYTE = 'b'
USHORT = 'H'
BYTES = 's'

HEADER_SIZE_BYTES = 4
PACKET_DATA_SIZE = 1024
PACKET_SIZE = PACKET_DATA_SIZE + HEADER_SIZE_BYTES
PACKET_TIMER = 1

MAX_SHORT = 2**16
ACK = 1
SYN = 2
FIN = 4
TYP = 8

WINDOW_SIZE = 100

PACKET_SIZE = PACKET_DATA_SIZE + HEADER_SIZE_BYTES

HKEY_ENTITY_RUN_POS = 0

HKEY_SEQ_NBR_BEGIN = 0

MAX_TIME_RECV_AWAIT = 5

HKEY_WINDOW_SIZE = 100
PACKET_TIMER = 1

LOSS = -1
